version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
  
    working_directory: ~/repo
    steps:
      - checkout
      
      - run: yarn install
    
      - run: npm run start & sleep 5; npm run test-pa11y

